apiVersion: v1
# Specifying the kind as Service 
# because we want to define our pod type to communicate with each other inside the cluster
kind: Service
metadata:
  name: node-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-web-app-pod
  ports:
  - protocol: TCP
    port: 5000 #port to connect to service
    targetPort: 3000 #portinside the container where the app will run
    nodePort: 31110 #external port to talk to